# Generated by Django 4.1 on 2022-09-03 18:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Elevator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.PositiveSmallIntegerField(choices=[(1, 'Working'), (2, 'In Maintenance'), (3, 'Not Working')], default=1)),
                ('floor', models.PositiveSmallIntegerField(default=0)),
                ('last_travel_direction', models.PositiveSmallIntegerField(choices=[(1, 'Up'), (2, 'Down'), (3, 'Stop')], default=3)),
            ],
        ),
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=264)),
            ],
        ),
        migrations.CreateModel(
            name='ElevatorTravelLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('request_from', models.PositiveSmallIntegerField(choices=[(1, 'Outside'), (2, 'Inside')], default=1)),
                ('request_status', models.PositiveSmallIntegerField(choices=[(1, 'Success'), (2, 'Failure')], default=1)),
                ('floor_from', models.PositiveSmallIntegerField(default=None)),
                ('floor_to', models.PositiveSmallIntegerField(default=None)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('elevator_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_system.elevator')),
                ('user_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='elevator_system.user')),
            ],
        ),
    ]
