# Generated by Django 4.1 on 2022-09-04 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0002_remove_elevatortravellog_user_id_delete_user'),
    ]

    operations = [
        migrations.AddField(
            model_name='elevatortravellog',
            name='failure_reason',
            field=models.PositiveSmallIntegerField(choices=[(1, 'None of the Elevators in available'), (2, 'All Working Elevators are stuck on some other floor, please try after some time'), (3, 'Invalid request')], default=None),
        ),
        migrations.AddField(
            model_name='elevatortravellog',
            name='request_door',
            field=models.PositiveSmallIntegerField(choices=[(1, 'open'), (2, 'close')], default=None),
        ),
    ]
