# Generated by Django 4.1 on 2022-09-04 12:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0003_elevatortravellog_failure_reason_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatortravellog',
            name='floor_from',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
        migrations.AlterField(
            model_name='elevatortravellog',
            name='floor_to',
            field=models.PositiveSmallIntegerField(default=None, null=True),
        ),
    ]
