# Generated by Django 4.1 on 2022-09-04 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('elevator_system', '0005_alter_elevatortravellog_failure_reason'),
    ]

    operations = [
        migrations.AlterField(
            model_name='elevatortravellog',
            name='request_door',
            field=models.PositiveSmallIntegerField(choices=[(1, 'open'), (2, 'close')], default=None, null=True),
        ),
    ]
